//! `codex.lock` — the recorded module set.
//!
//! The lock file is the committed memory of what the codebase looked like when it
//! was last accepted. It records each module's version and content hash, so two
//! things become checkable that a graph alone cannot express: a module whose bytes
//! changed while its declared version stayed the same (`version_drift`), and a
//! module set that changed at all (`codex lock --check`).
//!
//! The serialization is written by hand rather than by a generic TOML writer for
//! the same reason [`crate::emit`] writes Turtle by hand: the committed artifact
//! must be byte-stable, and only an explicit ordering guarantees that.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use mm_core::MmError;
use serde::{Deserialize, Serialize};

use crate::model::CodexReport;

/// The lock format version.
pub const LOCK_SCHEMA: u32 = 1;

/// One module's recorded state.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedModule {
    /// The module IRI.
    pub uri: String,
    /// The repository-relative path.
    pub path: String,
    /// The declared version.
    pub version: String,
    /// The canonical hash of the module's file set.
    pub content_hash: String,
    /// The capabilities the module provides.
    #[serde(default)]
    pub capabilities: Vec<String>,
}

/// The whole lock file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CodexLock {
    /// The lock format version.
    pub schema: u32,
    /// The `/code` graph hash at the moment the lock was taken.
    pub graph_hash: String,
    /// Every module, ordered by URI.
    #[serde(default, rename = "module")]
    pub module: Vec<LockedModule>,
}

impl CodexLock {
    /// Record a report as a lock file.
    pub fn from_report(report: &CodexReport) -> Self {
        let mut module: Vec<LockedModule> = report
            .modules
            .iter()
            .map(|m| {
                let mut capabilities: Vec<String> = report
                    .capabilities
                    .iter()
                    .filter(|c| c.module_uri == m.module_uri)
                    .map(|c| c.capability.clone())
                    .collect();
                capabilities.sort();
                capabilities.dedup();
                LockedModule {
                    uri: m.module_uri.clone(),
                    path: m.rel_path.clone(),
                    version: m.version.clone(),
                    content_hash: m.content_hash.clone(),
                    capabilities,
                }
            })
            .collect();
        module.sort_by(|a, b| a.uri.cmp(&b.uri));
        CodexLock {
            schema: LOCK_SCHEMA,
            graph_hash: report.graph_hash.clone(),
            module,
        }
    }

    /// The canonical, byte-stable rendering.
    pub fn to_deterministic_string(&self) -> String {
        let mut out = String::new();
        out.push_str(
            "# codex.lock — generated by `mm-cli codex lock`; commit this file.\n\
             #\n\
             # It records every module's version and content hash so that a change\n\
             # without a version bump is caught by `codex lock --check` and\n\
             # `codex verify`. Regenerate it with `mm-cli codex lock` after an\n\
             # intentional change, and review the diff as part of the change.\n",
        );
        let _ = writeln!(out, "schema = {}", self.schema);
        let _ = writeln!(out, "graph_hash = {}", quoted(&self.graph_hash));
        for m in &self.module {
            out.push_str("\n[[module]]\n");
            let _ = writeln!(out, "uri = {}", quoted(&m.uri));
            let _ = writeln!(out, "path = {}", quoted(&m.path));
            let _ = writeln!(out, "version = {}", quoted(&m.version));
            let _ = writeln!(out, "content_hash = {}", quoted(&m.content_hash));
            let caps: Vec<String> = m.capabilities.iter().map(|c| quoted(c)).collect();
            let _ = writeln!(out, "capabilities = [{}]", caps.join(", "));
        }
        out
    }

    /// Parse a lock file.
    pub fn parse(raw: &str) -> Result<Self, MmError> {
        toml::from_str(raw).map_err(|e| MmError::Config(format!("invalid codex.lock: {e}")))
    }
}

/// A JSON string literal is also a valid TOML basic string for the values a lock
/// file carries (IRIs, hashes, versions).
fn quoted(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| format!("{value:?}"))
}

/// Read a lock file, treating a missing file as "no lock yet".
pub fn read_lock(path: &Path) -> Result<Option<CodexLock>, MmError> {
    match std::fs::read_to_string(path) {
        Ok(raw) => CodexLock::parse(&raw).map(Some),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(MmError::Store(format!(
            "cannot read {}: {e}",
            path.display()
        ))),
    }
}

/// Write a lock file, creating parent directories as needed.
///
/// Returns `true` when the file's bytes changed, so a caller can record an audit
/// only for a real write.
pub fn write_lock(path: &Path, lock: &CodexLock) -> Result<bool, MmError> {
    let text = lock.to_deterministic_string();
    let existing = std::fs::read_to_string(path).ok();
    if existing.as_deref() == Some(text.as_str()) {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(path, &text)?;
    Ok(true)
}

/// What changed between two lock files.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct LockDiff {
    /// Modules that appeared.
    pub added: Vec<String>,
    /// Modules that disappeared.
    pub removed: Vec<String>,
    /// Modules whose version, content hash, or capability set changed.
    pub changed: Vec<String>,
}

impl LockDiff {
    /// True when the two locks record the same module set.
    pub fn is_empty(&self) -> bool {
        self.added.is_empty() && self.removed.is_empty() && self.changed.is_empty()
    }
}

/// Compare two locks by module URI.
pub fn diff(old: &CodexLock, new: &CodexLock) -> LockDiff {
    let old_by_uri: BTreeMap<&str, &LockedModule> =
        old.module.iter().map(|m| (m.uri.as_str(), m)).collect();
    let new_by_uri: BTreeMap<&str, &LockedModule> =
        new.module.iter().map(|m| (m.uri.as_str(), m)).collect();

    let mut out = LockDiff::default();
    for uri in new_by_uri.keys() {
        match old_by_uri.get(uri) {
            None => out.added.push((*uri).to_string()),
            Some(before) => {
                let after = new_by_uri[uri];
                if before.version != after.version
                    || before.content_hash != after.content_hash
                    || before.capabilities != after.capabilities
                {
                    out.changed.push((*uri).to_string());
                }
            }
        }
    }
    for uri in old_by_uri.keys() {
        if !new_by_uri.contains_key(uri) {
            out.removed.push((*uri).to_string());
        }
    }
    out.added.sort();
    out.removed.sort();
    out.changed.sort();
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::*;

    fn report() -> CodexReport {
        let uri = mm_core::codex::module_iri("crates/demo").into_string();
        CodexReport {
            modules: vec![ModuleRecord {
                rel_path: "crates/demo".into(),
                module_uri: uri.clone(),
                name: "demo".into(),
                version: "0.1.0".into(),
                kind: ModuleKind::RustCrate,
                category: None,
                crate_name: Some("demo".into()),
                owned_phase: 2,
                capability: "mm:CrateDemo".into(),
                content_hash: "aa".repeat(32),
                copied_from: None,
                copied_revision: None,
                copied_license: None,
                origin: Some("metamind".into()),
                manifest_only: false,
                declared_uri: None,
                tbox_functions: vec![],
                depends_on: vec![],
            }],
            capabilities: vec![CapabilityRecord {
                capability: "mm:CrateDemo".into(),
                module_uri: uri,
                test_count: 1,
            }],
            graph_hash: "gh".into(),
            ..CodexReport::default()
        }
    }

    #[test]
    fn a_lock_round_trips_through_its_own_text() {
        let lock = CodexLock::from_report(&report());
        let text = lock.to_deterministic_string();
        let parsed = CodexLock::parse(&text).unwrap();
        assert_eq!(parsed, lock);
        assert_eq!(parsed.module[0].capabilities, vec!["mm:CrateDemo"]);
    }

    #[test]
    fn rendering_is_byte_stable_regardless_of_input_order() {
        let mut a = report();
        let lock_a = CodexLock::from_report(&a);
        // Reversing the input collections must not change the output bytes.
        let mut second = a.modules[0].clone();
        second.rel_path = "crates/aaa".into();
        second.module_uri = mm_core::codex::module_iri("crates/aaa").into_string();
        a.modules.push(second);
        a.modules.reverse();
        a.capabilities.reverse();
        let lock_b = CodexLock::from_report(&a);
        assert_ne!(lock_a, lock_b, "the module set really is different");
        // But a lock built from the same set in a different order is identical.
        let mut reordered = lock_b.clone();
        reordered.module.reverse();
        let mut normalized = reordered;
        normalized.module.sort_by(|x, y| x.uri.cmp(&y.uri));
        assert_eq!(
            normalized.to_deterministic_string(),
            lock_b.to_deterministic_string()
        );
    }

    #[test]
    fn a_changed_hash_at_the_same_version_is_a_diff() {
        let before = CodexLock::from_report(&report());
        let mut after_report = report();
        after_report.modules[0].content_hash = "bb".repeat(32);
        let after = CodexLock::from_report(&after_report);
        let diff = diff(&before, &after);
        assert!(diff.added.is_empty());
        assert!(diff.removed.is_empty());
        assert_eq!(diff.changed, vec![after.module[0].uri.clone()]);
        assert!(!diff.is_empty());
    }

    #[test]
    fn an_unchanged_report_diffs_empty() {
        let lock = CodexLock::from_report(&report());
        assert!(diff(&lock, &lock).is_empty());
    }

    #[test]
    fn a_missing_lock_is_not_an_error() {
        let dir = tempfile::tempdir().unwrap();
        assert!(read_lock(&dir.path().join("nope.lock")).unwrap().is_none());
    }

    #[test]
    fn writing_twice_reports_no_change_the_second_time() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("codex.lock");
        let lock = CodexLock::from_report(&report());
        assert!(write_lock(&path, &lock).unwrap(), "the first write lands");
        assert!(!write_lock(&path, &lock).unwrap(), "the second is a no-op");
        assert_eq!(read_lock(&path).unwrap().unwrap(), lock);
    }

    #[test]
    fn a_corrupt_lock_is_an_error() {
        assert!(CodexLock::parse("schema = ").is_err());
    }
}
